version: '2'
services:
  bot:
    build:
      dockerfile: Dockerfile.bot
    restart: always

  sender:
    build:
      args:
        TOKEN: $BOT_TOKEN
      context: ./sender
      dockerfile: Dockerfile.sender
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
     - bot
    restart: always

  whisper:
    build:
      context: whisper
      dockerfile: Dockerfile.whisper
    env_file:
      - .env
    ports:
      - "${WHISPER_PORT}:5050"
    volumes:
      - 'whisper_data:/root/.cache/huggingface'
    restart: always

  lt-sender:
    image: efrecon/localtunnel
    command:
      --local-host sender -p 8081 -s $SENDER_SUBDOMAIN
    depends_on:
      - sender
    restart: always
      
volumes:
  whisper_data:
    driver: local