FROM python:3.10-slim

WORKDIR /app

RUN apt update
RUN apt-get update
RUN apt-get install xz-utils
RUN apt install -y wget
RUN pip install --upgrade pip

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

CMD ["python", "telegram-bot.py"]