version: '2'
services:
  bot:
    build:
      dockerfile: Dockerfile.bot

  sender:
    build:
      args:
        TOKEN: $BOT_TOKEN
      context: ./sender
      dockerfile: Dockerfile.sender
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
     - bot

  whisper:
    build:
      context: whisper
      dockerfile: Dockerfile.whisper
    env_file:
      - .env
    ports:
      - "5050:5050"
    volumes:
      - 'whisper_data:/root/.cache/huggingface'

  lt-sender:
    image: efrecon/localtunnel
    command:
      --local-host sender -p 8081 -s $SENDER_SUBDOMAIN
    depends_on:
      - sender
    restart: always

  lt-whisper:
    image: efrecon/localtunnel
    command:
      --local-host whisper -p 5050 -s $WHISPER_SUBDOMAIN
    depends_on:
      - whisper
    restart: always
      

volumes:
  whisper_data:
    driver: local