FROM python:3.9-buster

WORKDIR /app

RUN apt-get update
RUN apt-get install xz-utils
RUN apt install wget
RUN pip install --upgrade pip

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

CMD ["python", "telegram-bot.py"]