FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN apt update && apt-get install -y ffmpeg
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 5050

CMD ["python", "app.py"]